const DEFAULT_NUMBER_LENGTH = 3;
const DEFAULT_NUMBERS = 4;

const DEFAULT_TIME_TO_MEMORIZE = 60;
const DEFAULT_TIME_TO_WAIT = 60;

module.exports = {
  DEFAULT_NUMBER_LENGTH,
  DEFAULT_NUMBERS,
  DEFAULT_TIME_TO_MEMORIZE,
  DEFAULT_TIME_TO_WAIT,
};
